[signet]
# Custom Signet dedicated for the Coinswap Network. 
# This signet is maintained by Citadel FOSS Developers.
signetchallenge=0014a3ec9c731da66d9725d54947aede5c830623f33d
addnode=170.75.166.88:38333
dnsseed=0

# RPC Configurations for Coinswap operations
server=1
rpcuser=user
rpcpassword=password
rpcport=38332
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

# ZMQ Configurations for real-time transaction and block notifications
# Needed for the Watchers.
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332

# Required indexes for faster wallet sync
txindex=1
blockfilterindex=1

[regtest]
# Regtest network configurations for running Coinswap Taker and Maker
fallbackfee=0.00001000

# RPC Configurations for Coinswap operations
server=1
rpcuser=user
rpcpassword=password
rpcport=18442
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

# ZMQ Configurations for real-time transaction and block notifications
# Needed for the Watchers.
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28332

# Required indexes for faster wallet sync
txindex=1
blockfilterindex=1
